sonar.projectKey=addressbook
sonar.projectName=AddressBook CICD
sonar.projectVersion=1.0
sonar.sources=.
sonar.java.binaries=target/classes
sonar.token=sqa_f684cfe52f863140d872012ea8214ba7903962e2
sonar.host.url=http://65.1.127.151:9000
